#   Copyright 2026 UCP Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

"""MkDocs plugin to generate API documentation from OpenAPI and JSON Schemas.

This module defines custom macros for MkDocs (`schema_fields`,
`extension_schema_fields`, `extension_fields`, `auto_generate_schema_reference`,
`method_fields` and `header_fields`) that parse OpenAPI specifications and JSON
schema files to automatically generate Markdown tables for API request and
response bodies.

Schema layout
-------------
    source/schemas/
      *.json            Protocol schemas (ucp.json, capability.json, ...).
      common/           Cross-vertical schemas, plus common/types/.
      transports/       Transport envelopes.
      <vertical>/       Every other sub-directory is a vertical (shopping,
      <vertical>/types/ food, lodging, ...). Verticals are discovered from
                        the filesystem; none of them is special.

Schema resolution
-----------------
A `$ref` (or a schema name passed to a macro) is resolved to one concrete file:

  1. relative to the file containing the `$ref` (standard JSON Schema
     semantics), which is exact even when verticals share file names
     (e.g. `food/fulfillment.json` vs `shopping/fulfillment.json`);
  2. otherwise by name, searching the protocol and common directories, then
     the active vertical, then -- only if the match is unambiguous -- any
     other vertical.

Cross-reference links
---------------------
Every type link emitted inside a table points at the page that renders the
table for that exact schema file:

  * `common/` schemas                 -> Schema Reference page.
  * schema rendered on current page   -> same-page anchor.
  * vertical schema, on reference.md  -> path-qualified reference anchor.
  * vertical schema rendered on a
    specification page                -> that page (overview pages before
                                         sub-pages, then nav order).
  * vertical schema rendered nowhere  -> path-qualified reference anchor.
  * anything else (ucp.json, ...)     -> current page.

Path-qualified reference anchors (e.g. `#food-types-fulfillment`) are emitted
by `auto_generate_schema_reference` so that schemas sharing a title across or
within verticals (e.g. "Fulfillment") remain individually addressable.
"""

import dataclasses
import json
import os
from pathlib import Path
import re
import subprocess
from typing import Any

# --- CONFIGURATION ---
# Base directories for schema resolution.
OPENAPI_DIR = Path("source/services")
SCHEMAS_DIR = Path("source/schemas")
HANDLERS_GOOGLE_PAY_DIR = Path("source/handlers/google_pay")
COMMON_SCHEMAS_DIR = SCHEMAS_DIR / "common"
COMMON_TYPES_DIR = COMMON_SCHEMAS_DIR / "types"
UCP_SCHEMA_PATH = SCHEMAS_DIR / "ucp.json"
SPEC_DOCS_DIR = Path("docs/specification")

# Page (relative to docs/specification, without `.md`) hosting the schema
# reference generated by `auto_generate_schema_reference`.
REFERENCE_PAGE = "reference"
REFERENCE_DOC_PATH = SPEC_DOCS_DIR / f"{REFERENCE_PAGE}.md"

# Sub-directories of source/schemas/ that are protocol namespaces rather than
# verticals. Every other sub-directory is treated as a vertical.
PROTOCOL_NAMESPACES = ("common", "transports")

# Variant suffixes accepted by `schema_fields` (e.g. `cart_create_req`).
_REQUEST_OPERATIONS = ("create", "update", "complete", "read")

# Matches `https://ucp.dev/schemas/<path>.json` style `$id`s and refs.
_SCHEMA_URL_RE = re.compile(r"/schemas/(.+\.json)$")

# Macros whose first argument names a schema rendered on the calling page.
_SCHEMA_MACRO_RE = re.compile(
  r"""\{\{\s*(schema_fields|extension_schema_fields|extension_fields)\s*"""
  r"""\(\s*['"]([^'"]+)['"]"""
)


# --- VERTICALS ---
def _discover_verticals() -> tuple[str, ...]:
  """Return every sub-directory of SCHEMAS_DIR that is a vertical."""
  if not SCHEMAS_DIR.is_dir():
    return ()
  return tuple(
    sorted(
      p.name
      for p in SCHEMAS_DIR.iterdir()
      if p.is_dir() and p.name not in PROTOCOL_NAMESPACES
    )
  )


VERTICALS = _discover_verticals()


def _namespace_dirs(namespace: str) -> list[Path]:
  """Return `<namespace>/` and, if present, `<namespace>/types/`."""
  root = SCHEMAS_DIR / namespace
  return [root, *([root / "types"] if (root / "types").is_dir() else [])]


# Directories searched (in order) for every name-based lookup.
PROTOCOL_SEARCH_DIRS = [
  HANDLERS_GOOGLE_PAY_DIR,
  SCHEMAS_DIR,
  *(d for ns in PROTOCOL_NAMESPACES for d in _namespace_dirs(ns)),
]
VERTICAL_SEARCH_DIRS = {v: _namespace_dirs(v) for v in VERTICALS}


def vertical_of(path: Path | str | None) -> str | None:
  """Return the vertical owning a schema/OpenAPI file, or None."""
  if path is None:
    return None
  path = Path(path)
  for root in (SCHEMAS_DIR, OPENAPI_DIR):
    try:
      parts = path.relative_to(root).parts
    except ValueError:
      continue
    if len(parts) > 1 and parts[0] in VERTICALS:
      return parts[0]
  return None


def _is_within(path: Path, directory: Path) -> bool:
  return directory == path or directory in path.parents


def _vertical_of_page(page: str | None) -> str | None:
  """Return the vertical of a spec page id (e.g. 'food/checkout')."""
  head = (page or "").split("/", 1)[0]
  return head if head in VERTICALS else None


def _validate_common_namespace_exclusivity() -> None:
  """Fail fast if any vertical schema shadows a common-namespace filename.

  Name-based lookups (macro arguments, legacy refs) search the common
  namespace before the active vertical, so a vertical file sharing a basename
  with a common/ file (top-level or types/) could never be reached by name and
  would silently resolve to the common file. Verticals are autonomous siblings
  and may freely share filenames with each other -- name-based lookups are
  vertical-scoped and `$ref`s resolve by path -- so this guard only protects
  the common namespace.
  """
  common_names = {
    p.name: p for d in _namespace_dirs("common") for p in d.glob("*.json")
  }
  for vertical_dirs in VERTICAL_SEARCH_DIRS.values():
    for d in vertical_dirs:
      for p in d.glob("*.json"):
        if p.name in common_names:
          raise RuntimeError(
            f"Schema filename '{p.name}' is claimed by common "
            f"({common_names[p.name]}) and shadowed by {p}. Once a "
            "basename exists in common/ (top-level or types/), no vertical "
            "may reuse it -- name-based doc resolution would silently bind "
            "to the common file. Rename or remove the vertical file. "
            "Verticals may share filenames with each other; this rule only "
            "protects common."
          )


_validate_common_namespace_exclusivity()


# --- SCHEMA FILE RESOLUTION ---
def _normalize(path: Path | str) -> Path:
  """Collapse `..` segments so equal files compare equal."""
  return Path(os.path.normpath(path))


def find_schema(name: str, vertical: str | None = None) -> Path | None:
  """Find a schema file by (optionally path-qualified) name.

  Args:
  ----
    name: e.g. 'buyer', 'types/buyer', 'food/types/buyer.json' or
      '../common/types/payment_instrument.json'.
    vertical: Vertical whose directories are searched after the protocol
      directories.

  Returns:
  -------
    The matching file, or None if no file matches.

  Raises:
  ------
    LookupError: If `name` is only found outside `vertical` and matches
      files in more than one vertical.

  """
  filename = name if name.endswith(".json") else f"{name}.json"
  for directory in PROTOCOL_SEARCH_DIRS + VERTICAL_SEARCH_DIRS.get(
    vertical, []
  ):
    candidate = _normalize(directory / filename)
    if candidate.is_file():
      return candidate

  # Not in the active vertical: accept another vertical's file only when the
  # name is unambiguous, so collisions never resolve to the wrong vertical.
  matches = sorted(
    {
      candidate
      for other, dirs in VERTICAL_SEARCH_DIRS.items()
      if other != vertical
      for d in dirs
      if (candidate := _normalize(d / filename)).is_file()
    }
  )
  if len(matches) > 1:
    raise LookupError(
      f"Schema name '{name}' is ambiguous across verticals "
      f"({', '.join(map(str, matches))}). Qualify it with the vertical "
      "(e.g. 'food/types/buyer') or call it from a vertical page."
    )
  return matches[0] if matches else None


def schema_path_from_url(url: str | None) -> Path | None:
  """Map a `https://ucp.dev/schemas/...json` URL to its source file."""
  match = _SCHEMA_URL_RE.search(url or "")
  if not match:
    return None
  candidate = _normalize(SCHEMAS_DIR / match.group(1))
  return candidate if candidate.is_file() else None


def resolve_ref(
  ref: str, base: Path | None = None, vertical: str | None = None
) -> Path | None:
  """Resolve a `$ref` (or schema name) to the schema file it designates.

  Args:
  ----
    ref: The reference, optionally with a `#...` fragment.
    base: The file containing the reference, if known.
    vertical: Vertical used for the name-based fallback.

  Returns:
  -------
    The referenced file, or None if it cannot be found locally.

  """
  path_part = ref.split("#", 1)[0]
  if not path_part:
    return base  # Internal reference such as `#/$defs/foo`.
  if path_part.startswith(("http://", "https://")):
    return schema_path_from_url(path_part)
  if base is not None:
    candidate = _normalize(base.parent / path_part)
    if candidate.is_file():
      return candidate
  return find_schema(path_part, vertical or vertical_of(base))


def parse_entity_name(entity_name: str) -> tuple[str, str, str]:
  """Split a `schema_fields` argument into (name, direction, operation).

  'cart_resp' -> ('cart', 'response', 'read'),
  'cart_create_req' -> ('cart', 'request', 'create'),
  'buyer' -> ('buyer', 'response', 'read').
  """
  if entity_name.endswith("_resp"):
    return entity_name[: -len("_resp")], "response", "read"
  if entity_name.endswith("_req"):
    stem = entity_name[: -len("_req")]
    name, _, operation = stem.rpartition("_")
    if name and operation in _REQUEST_OPERATIONS:
      return name, "request", operation
    return stem, "request", "read"
  return entity_name, "response", "read"


# --- SPECIFICATION PAGE INDEX ---


def _page_id(src_path: str) -> str:
  """Turn 'shopping/checkout/index.md' into the page id 'shopping/checkout'."""
  page = src_path.removeprefix("specification/").removesuffix(".md")
  return page.removesuffix("/index")


def _flatten_nav(nav: Any) -> list[str]:
  """Return the Markdown sources referenced by an MkDocs nav, in order."""
  if isinstance(nav, str):
    return [nav] if nav.endswith(".md") else []
  if isinstance(nav, dict):
    nav = list(nav.values())
  if isinstance(nav, list):
    return [src for item in nav for src in _flatten_nav(item)]
  return []


def _macro_schema_path(
  macro: str, entity: str, vertical: str | None
) -> Path | None:
  """Return the schema file a doc macro call renders, if resolvable."""
  if macro == "schema_fields":
    name = parse_entity_name(entity)[0]
  else:
    name = entity.split("#", 1)[0]
  try:
    return find_schema(name, vertical)
  except LookupError:
    return None  # Rendering the page reports the ambiguity.


@dataclasses.dataclass(frozen=True)
class SpecPageIndex:
  """Which specification pages render a table for which schema files.

  Attributes:
    pages: Every page id under docs/specification.
    hosted: Page id -> schema files rendered on that page by a macro.
    canonical: Schema file -> preferred page to deep-link to.

  """

  pages: frozenset[str]
  hosted: dict[str, frozenset[Path]]
  canonical: dict[Path, str]

  def hosts(self, page: str, schema: Path) -> bool:
    """Whether `page` renders a table for `schema`."""
    return schema in self.hosted.get(page, ())


def build_spec_page_index(nav: Any = None) -> SpecPageIndex:
  """Scan docs/specification for schema macros and index their pages.

  The canonical page for a schema is the first page rendering it, preferring
  overview pages over their sub-pages (e.g. `checkout` over
  `checkout/embedded`), then MkDocs nav order, then page id.
  """
  nav_rank = {_page_id(src): i for i, src in enumerate(_flatten_nav(nav or []))}
  pages: set[str] = set()
  subpages: set[str] = set()
  hosted: dict[str, set[Path]] = {}

  if SPEC_DOCS_DIR.is_dir():
    for md_file in sorted(SPEC_DOCS_DIR.rglob("*.md")):
      page = _page_id(md_file.relative_to(SPEC_DOCS_DIR).as_posix())
      pages.add(page)
      if md_file.name != "index.md" and (md_file.parent / "index.md").exists():
        subpages.add(page)
      vertical = _vertical_of_page(page)
      content = md_file.read_text(encoding="utf-8")
      for macro, entity in _SCHEMA_MACRO_RE.findall(content):
        schema = _macro_schema_path(macro, entity, vertical)
        if schema is not None:
          hosted.setdefault(page, set()).add(schema)

  def rank(page: str) -> tuple[bool, int, str]:
    return (page in subpages, nav_rank.get(page, len(nav_rank)), page)

  canonical: dict[Path, str] = {}
  for page in sorted(hosted, key=rank):
    if page == REFERENCE_PAGE:
      continue  # The reference page is addressed via qualified anchors.
    for schema in hosted[page]:
      canonical.setdefault(schema, page)

  return SpecPageIndex(
    pages=frozenset(pages),
    hosted={page: frozenset(s) for page, s in hosted.items()},
    canonical=canonical,
  )


# --- LINK LABELS & ANCHORS ---


def _humanize(name: str) -> str:
  return name.replace("_", " ").replace(".", " ").replace("-", " ").title()


def _slug(name: str) -> str:
  return name.replace("_", "-").lower()


def reference_anchor(schema: Path, fragment: str | None = None) -> str | None:
  """Path-qualified anchor of a vertical schema on the reference page.

  The anchor encodes the schema's full path so it is unique even when names
  collide across verticals or within one (extension vs. type), e.g.
  `food/fulfillment.json` -> 'food-fulfillment',
  `food/types/fulfillment.json` -> 'food-types-fulfillment' and
  `shopping/discount.json#/$defs/allocation` -> 'shopping-discount-allocation'.
  """
  if vertical_of(schema) is None:
    return None
  rel = schema.relative_to(SCHEMAS_DIR).with_suffix("")
  anchor = _slug("-".join(rel.parts))
  return f"{anchor}-{_slug(fragment)}" if fragment else anchor


def _reference_anchor_tag(schema: Path, fragment: str | None = None) -> str:
  """Inline HTML anchor appended to reference-page headings (may be '')."""
  anchor = reference_anchor(schema, fragment)
  return f' <span id="{anchor}"></span>' if anchor else ""


def _link_text(raw_name: str, fragment: str | None, is_ucp: bool) -> str:
  """Visible text of a type link, e.g. 'Checkout Response'."""
  if fragment:
    text = f"{_humanize(raw_name)} {_humanize(fragment)}".strip()
  else:
    text = _humanize(raw_name)

  if text.endswith("Resp"):
    text = text.replace("Resp", "Response")
  elif text.endswith("Req"):
    text = text.replace("Req", "Request")

  # Explicitly add UCP prefix for core UCP definitions if missing.
  if is_ucp and "Ucp" not in text and "UCP" not in text:
    text = f"UCP {text}"
  return text


def _link_anchor(raw_name: str, fragment: str | None, is_ucp: bool) -> str:
  """Anchor matching the Markdown heading that documents a schema.

  e.g. 'line_item.create_req' -> 'line-item-create-request' ("Line Item" H3 ->
  "Create Request" H4) and 'pagination' + 'response' -> 'pagination-response'.
  """
  parts = raw_name.split(".")
  anchor = parts[0].replace("_", "-")

  if fragment:
    fragment_anchor = fragment.replace("_", "-")
    # External ref -> 'base-fragment'; internal ref (#/$defs/x) -> 'fragment'.
    anchor = f"{anchor}-{fragment_anchor}" if anchor else fragment_anchor
  elif len(parts) > 1:
    variant = (
      parts[1]
      .replace("create_req", "create-request")
      .replace("update_req", "update-request")
      .replace("resp", "response")
      .replace("-", " ")
    )
    anchor = f"{anchor}-{variant}".replace(" ", "-")
  elif raw_name.endswith("_resp"):
    anchor = raw_name.replace("_", "-").replace("-resp", "-response")
  elif raw_name.endswith("_req"):
    anchor = raw_name.replace("_", "-").replace("-req", "-request")

  # Ensure anchor starts with ucp- for UCP definitions.
  if is_ucp and not anchor.startswith("ucp-"):
    anchor = f"ucp-{anchor}"
  return anchor.removeprefix("#").lower()


# --- TABLE HELPERS ---


def _field_requirement(field_name, ucp_request, required_list):
  """Render the Requirement cell for a schema field.

  The base ``required`` array defines the *response* requirement
  (responses never omit a defined field, so a field is either
  ``required`` or ``optional`` in responses). The ``ucp_request``
  annotation overrides the *request* requirement — either a single
  value applied to every request operation, or a per-operation map over
  ``create``/``update``/``complete``. Request operations left
  unannotated inherit the response requirement.

  The response requirement is the default: request operations that
  share it are omitted from the cell, so only the *differences* are
  spelled out. Returns a
  Markdown string such as ``**Required**`` (same everywhere) or
  ``**Required**; optional on update``.
  """
  word = {"required": "required", "optional": "optional", "omit": "omitted"}
  response = "required" if field_name in required_list else "optional"
  base_disp = "**Required**" if response == "required" else "Optional"

  if ucp_request is None:
    return base_disp

  if isinstance(ucp_request, str):
    if ucp_request == response:
      return base_disp
    return f"{base_disp}; {word.get(ucp_request, ucp_request)} in requests"

  if isinstance(ucp_request, dict):
    # Only keep operations whose requirement differs from the response
    # default; the rest inherit it and would be redundant to spell out.
    diff_request = {}
    for op in ("create", "update", "complete"):
      val = ucp_request.get(op)
      if val:
        disp_val = None
        if isinstance(val, str):
          if val != response:
            disp_val = word.get(val, val)
        elif isinstance(val, dict) and "transition" in val:
          transition = val["transition"]
          to_state = transition.get("to")
          from_state = transition.get("from")
          from_disp = word.get(from_state, from_state)
          to_disp = word.get(to_state, to_state)
          disp_val = f"transitioning from {from_disp} to {to_disp}"

        if disp_val:
          diff_request[op] = disp_val

    if not diff_request:
      return base_disp

    # Group adjacent request operations that share a requirement value so the
    # cell stays compact (e.g. "required on create & update").
    groups = []  # list of (value, [ops]) preserving operation order
    for op in ("create", "update", "complete"):
      if op not in diff_request:
        continue
      val = diff_request[op]
      if groups and groups[-1][0] == val:
        groups[-1][1].append(op)
      else:
        groups.append((val, [op]))
    clauses = [f"{val} on {' & '.join(ops)}" for val, ops in groups]
    if not clauses:
      return base_disp
    return f"{base_disp}; {', '.join(clauses)}"

  return base_disp


def _merge_cells(new_parts: list[str], prior: list[str]) -> list[str]:
  """Merge two renderings of the same field, cell by cell.

  - Type (col 2): "any" is the renderer's placeholder for a branch that adds
    no `type`, which defers to the base branch. Also, generic "string" in a
    specialization should not overwrite a more specific referenced type from
    the base branch.
  - Description (col 4): merge specialization description with base
    description so protocol rules from base are not lost.
  """
  merged = list(new_parts)
  for i, new_val in enumerate(new_parts):
    old_val = prior[i] if i < len(prior) else ""
    if i == 2:  # Type column
      if new_val and new_val != "any":
        if new_val == "string" and old_val and old_val not in ("any", "string"):
          merged[i] = old_val
        else:
          merged[i] = new_val
      else:
        merged[i] = old_val or new_val
    elif i == 4:  # Description column
      if new_val and old_val and new_val != old_val:
        if old_val in new_val:
          merged[i] = new_val
        elif new_val in old_val:
          merged[i] = old_val
        else:
          sep = " " if new_val.endswith((".", "!", "?")) else ". "
          merged[i] = f"{new_val}{sep}{old_val}"
      else:
        merged[i] = new_val or old_val
    else:
      merged[i] = (
        new_val if new_val and new_val != "any" else (old_val or new_val)
      )
  return merged


def _dedupe_table_rows(blocks: list[str]) -> str:
  """Combine rendered allOf branches, emitting each field row only once.

  When allOf composition overrides a property from an earlier branch, prefer
  the outer (later) definition per cell, falling back to the base branch for
  cells the specialization leaves empty.
  """
  rows: dict[str, list[str]] = {}
  other_lines = []
  for block in blocks:
    for line in block.splitlines():
      stripped = line.strip()
      if not stripped:
        continue
      is_row = (
        stripped.startswith("|")
        and stripped.endswith("|")
        and not stripped.endswith(r"\|")
      )
      if is_row:
        parts = [p.strip() for p in re.split(r"(?<!\\)\|", stripped)]
        # Exclude header and separator rows if any were embedded.
        if len(parts) >= 5 and parts[1] not in ("Name", ":---"):
          field_name = parts[1]
          prior = rows.get(field_name)
          rows[field_name] = (
            parts if prior is None else _merge_cells(parts, prior)
          )
          continue
      other_lines.append(line)

  result = ["| " + " | ".join(p[1:-1]) + " |" for p in rows.values()]
  result.extend(other_lines)
  return "\n".join(result)


# --- JSON & UCP-SCHEMA HELPERS ---
# These are thin wrappers; actual schema resolution is done by ucp-schema CLI.

# Cache for resolved schemas to avoid repeated subprocess calls.
_resolved_schema_cache: dict[str, dict] = {}


def _load_json(path: str | Path | None) -> dict[str, Any] | None:
  """Load JSON file, returns None on error."""
  if path is None:
    return None
  try:
    with Path(path).open(encoding="utf-8") as f:
      return json.load(f)
  except (json.JSONDecodeError, OSError):
    return None


def _resolve_json_pointer(pointer: str, data: Any) -> Any | None:
  """Navigate to a JSON pointer path (e.g., '#/$defs/foo' or '#/components/x').

  Args:
  ----
    pointer: JSON pointer starting with '#' (e.g., '#/$defs/allocation').
    data: The JSON data to navigate.

  Returns:
  -------
    The value at the pointer path, or None if not found.

  """
  if pointer == "#":
    return data
  if not pointer.startswith("#/"):
    return None

  current = data
  for part in pointer[2:].split("/"):
    if isinstance(current, dict) and part in current:
      current = current[part]
    elif isinstance(current, list):
      try:
        current = current[int(part)]
      except (ValueError, IndexError):
        return None
    else:
      return None
  return current


def _resolve_internal_all_of(schema: dict, root: Any) -> dict:
  """Inline `allOf` members that are internal (`#/...`) refs into `root`."""
  if "allOf" not in schema:
    return schema
  resolved_all_of = []
  for item in schema["allOf"]:
    if "$ref" in item and item["$ref"].startswith("#"):
      resolved = _resolve_json_pointer(item["$ref"], root)
      resolved_all_of.append(resolved if resolved else item)
    else:
      resolved_all_of.append(item)
  return {**schema, "allOf": resolved_all_of}


def _resolve_schema(
  schema_path: str | Path,
  direction: str = "response",
  operation: str = "read",
  bundle: bool = False,
) -> dict[str, Any] | None:
  """Resolve a schema using ucp-schema CLI.

  Args:
  ----
    schema_path: Path to the schema file.
    direction: 'request' or 'response'.
    operation: 'create', 'update', 'complete', or 'read'.
    bundle: If True, inline all $ref pointers. If False, preserve $refs for
      hyperlink generation in documentation.

  Returns:
  -------
    Resolved schema as dict, or raises RuntimeError if ucp-schema fails.

  """
  bundle_suffix = ":bundled" if bundle else ""
  cache_key = f"{schema_path}:{direction}:{operation}{bundle_suffix}"
  if cache_key in _resolved_schema_cache:
    return _resolved_schema_cache[cache_key]

  dir_flag = "--request" if direction == "request" else "--response"
  cmd = ["ucp-schema", "resolve", str(schema_path), dir_flag, "--op", operation]
  if bundle:
    cmd.append("--bundle")

  result = subprocess.run(cmd, capture_output=True, text=True, check=False)
  if result.returncode != 0:
    raise RuntimeError(f"ucp-schema execution error: result = {result}")
  data = json.loads(result.stdout)
  _resolved_schema_cache[cache_key] = data
  return data


# --- RENDER CONTEXT ---


@dataclasses.dataclass(frozen=True)
class RenderContext:
  """State threaded through recursive table rendering.

  Attributes:
    io_type: 'request' or 'response' to render an operation-specific view
      (resolved through ucp-schema); None renders schemas as authored.
    operation_id: Operation (or operationId) selecting the ucp-schema `--op`.
    base: Schema/OpenAPI file whose relative `$ref`s are being rendered.
    vertical: Vertical of the calling page, used to resolve bare schema
      names when `base` cannot.

  """

  io_type: str | None = None
  operation_id: str = ""
  base: Path | None = None
  vertical: str | None = None

  def at(self, base: Path | None) -> "RenderContext":
    """Return a copy rendering refs relative to `base` (if given)."""
    return dataclasses.replace(self, base=base) if base else self

  @property
  def lookup_vertical(self) -> str | None:
    """Vertical used for name-based lookups: the base's, else the page's."""
    return vertical_of(self.base) or self.vertical

  @property
  def operation(self) -> str:
    """The ucp-schema `--op` value for this context."""
    if self.io_type != "request":
      return "read"
    op_id = self.operation_id.lower()
    if "create" in op_id:
      return "create"
    if "update" in op_id or "patch" in op_id:
      return "update"
    if "complete" in op_id:
      return "complete"
    return "read"


# --- OPENAPI HELPERS ---


def _load_openapi(file_name: str) -> dict[str, Any]:
  with (OPENAPI_DIR / file_name).open(encoding="utf-8") as f:
    return json.load(f)


def _find_operation(
  data: dict, operation_id: str, include_webhooks: bool
) -> tuple[dict | None, list]:
  """Find an operation by id; return it with its path-level parameters."""
  sections = [data.get("paths", {})]
  if include_webhooks:
    sections.append(data.get("webhooks", {}))  # OpenAPI 3.1+
  for section in sections:
    for path_item in section.values():
      for op_data in path_item.values():
        if isinstance(op_data, dict) and (
          op_data.get("operationId") == operation_id
        ):
          return op_data, path_item.get("parameters", [])
  return None, []


def _restore_fragment_refs(
  bundled_def: dict[str, Any], raw_def: dict[str, Any] | None
) -> dict[str, Any]:
  """Restore cross-file `$defs` fragment refs that bundling left unlinked.

  Bundling inlines every `$ref`. A ref to a whole schema file keeps that
  file's `$id`, which the table renderer turns back into a type link, but a
  ref into another file's `$defs` fragment (e.g.
  `types/pagination.json#/$defs/request`) is inlined without one, so its Type
  cell falls back to `object`. Copy such refs from the unbundled definition
  onto the matching bundled properties (and their array `items`). Same-file
  refs (`#/$defs/...`) are left alone: only some of the pages that render
  them define a matching anchor, and `create_link` cannot tell which.
  `ucp.json` fragments are skipped too: the renderer inlines those itself.

  Args:
    bundled_def: The bundled definition to be rendered.
    raw_def: The same definition resolved without bundling.

  Returns:
    bundled_def, with fragment refs restored where they were lost.

  """
  props = bundled_def.get("properties")
  if not isinstance(raw_def, dict) or not isinstance(props, dict):
    return bundled_def
  raw_props = raw_def.get("properties") or {}

  def _lost_fragment_ref(bundled, raw):
    if not isinstance(bundled, dict) or not isinstance(raw, dict):
      return None
    ref = raw.get("$ref", "")
    if (
      "#/$defs/" in ref
      and not ref.startswith("#")
      and "ucp.json" not in ref
      and "$ref" not in bundled
      and "$id" not in bundled
    ):
      return ref
    return None

  restored = {}
  for name, details in props.items():
    raw = raw_props.get(name)
    ref = _lost_fragment_ref(details, raw)
    if ref:
      details = {**details, "$ref": ref}
    elif isinstance(details, dict) and isinstance(raw, dict):
      items_ref = _lost_fragment_ref(details.get("items"), raw.get("items"))
      if items_ref:
        details = {**details, "items": {**details["items"], "$ref": items_ref}}
    restored[name] = details
  return {**bundled_def, "properties": restored}


def define_env(env):
  """Injects custom macros into the MkDocs environment.

  This function is called by MkDocs and receives the `env` object,
  allowing it to register custom macros like `schema_fields` and
  `method_fields` for use in Markdown pages.

  Args:
  ----
    env: The MkDocs environment object.

  """
  nav = getattr(env, "conf", {}).get("nav")
  page_index = build_spec_page_index(nav)

  ucp_type_index: dict[str, Any] = {}

  def _ucp_type_index() -> dict[str, Any]:
    """Load ucp.json $defs and the anchors reference.md defines for them."""
    if not ucp_type_index:
      ucp_type_index["defs"] = (_load_json(UCP_SCHEMA_PATH) or {}).get(
        "$defs", {}
      )
      try:
        reference_md = REFERENCE_DOC_PATH.read_text(encoding="utf-8")
      except OSError:
        reference_md = ""
      ucp_type_index["anchors"] = set(
        re.findall(r"\{: #(ucp-[a-z0-9-]+) \}", reference_md)
      )
    return ucp_type_index

  def _ucp_def_type(def_name: str) -> str:
    """Type cell for a field typed by a ucp.json $def.

    Links to the reference section anchored for the def (e.g.
    `{: #ucp-response-checkout-schema }`) when one exists, otherwise names
    the def by its title, so the cell never falls back to "any".
    """
    index = _ucp_type_index()
    resolved_def = index["defs"].get(def_name, {})
    title = resolved_def.get("title") or (
      "UCP " + def_name.replace("_", " ").title()
    )
    anchor = "ucp-" + def_name.replace("_", "-")
    if anchor in index["anchors"]:
      return f"[{title}](site:specification/reference/#{anchor})"
    return title

  def _ucp_def_name_for_title(title: str | None) -> str | None:
    """Find the ucp.json $def a bundled (already inlined) schema came from."""
    if not title:
      return None
    for def_name, def_schema in _ucp_type_index()["defs"].items():
      if isinstance(def_schema, dict) and def_schema.get("title") == title:
        return def_name
    return None

  # --- Page context ---
  def get_error_context():
    try:
      return f" (in file: {env.page.file.src_path})"
    except AttributeError:
      return ""

  def _env_page_id() -> str | None:
    try:
      return _page_id(env.page.file.src_path)
    except AttributeError:
      return None

  def _page_vertical(spec_file_name: str | None) -> str | None:
    """Vertical of the calling page (from spec_file_name or the page path)."""
    return _vertical_of_page(spec_file_name) or _vertical_of_page(
      _env_page_id()
    )

  def _current_page(spec_file_name: str) -> str:
    """Page that same-page links resolve against."""
    if spec_file_name in page_index.pages:
      return spec_file_name
    return _env_page_id() or spec_file_name

  def _resolve(ref: str, ctx: "RenderContext") -> Path | None:
    """Resolve `ref` within `ctx`; ambiguity errors carry the page."""
    try:
      return resolve_ref(ref, ctx.base, ctx.lookup_vertical)
    except LookupError as e:
      raise LookupError(f"{e}{get_error_context()}") from e

  def _load_schema(path: Path, ctx: RenderContext) -> dict | None:
    """Load a schema, resolved for ctx's operation when io_type is set."""
    if not ctx.io_type:
      return _load_json(path)
    # No fallback to raw JSON: annotations must be resolved by ucp-schema.
    return _resolve_schema(path, ctx.io_type, ctx.operation)

  # --- Links ---
  _polymorphic_cache: dict[Path, bool] = {}

  def _is_polymorphic_type(ref_string: str, ctx: RenderContext) -> bool:
    """Check if a types/ schema is polymorphic (has ucp_request annotations).

    Polymorphic types have different request/response variants and require
    the -response suffix in anchors to match markdown headings.
    """
    if "types/" not in ref_string:
      return False
    path = _resolve(ref_string, ctx)
    if path is None:
      return False
    if path not in _polymorphic_cache:
      properties = (_load_json(path) or {}).get("properties", {})
      _polymorphic_cache[path] = any(
        isinstance(details, dict) and "ucp_request" in details
        for details in properties.values()
      )
    return _polymorphic_cache[path]

  def _link_destination(
    target: Path | None,
    ref_path: str,
    fragment: str | None,
    spec_file_name: str,
    anchor: str,
  ) -> tuple[str, str]:
    """Pick the (page, anchor) documenting `target` (see module docstring)."""
    current_page = _current_page(spec_file_name)
    if target is None:
      looks_common = "/common/" in ref_path or ref_path.startswith("common/")
      return (REFERENCE_PAGE if looks_common else current_page), anchor

    if not _is_within(target, SCHEMAS_DIR) or vertical_of(target) is None:
      # Common files canonically live on the reference page; internal refs
      # (`#/...`) of common, protocol (ucp.json, ...) and OpenAPI documents
      # stay on the page rendering that document.
      is_internal = not ref_path.split("#", 1)[0]
      if not is_internal and _is_within(target, COMMON_SCHEMAS_DIR):
        return REFERENCE_PAGE, anchor
      return current_page, anchor

    # Vertical schema: route by the exact file, never by its basename.
    if page_index.hosts(current_page, target):
      return current_page, anchor
    if current_page != REFERENCE_PAGE and target in page_index.canonical:
      return page_index.canonical[target], anchor
    return REFERENCE_PAGE, reference_anchor(target, fragment)

  def create_link(ref_string, spec_file_name, ctx=None):
    """Transform a schema reference into a Markdown link.

    Args:
    ----
      ref_string: e.g. "types/line_item.json",
        "../../common/types/pagination.json#/$defs/response" or
        "#/$defs/allocation".
      spec_file_name: The page the link is rendered on, e.g.
        "shopping/checkout".
      ctx: Optional RenderContext of the table containing the link. Its
        `base` resolves relative refs; its `io_type` drives polymorphic
        labels.

    Returns:
    -------
      Markdown link, e.g.
      [Line Item](site:specification/shopping/checkout/#line-item).

    """
    ctx = ctx or RenderContext(vertical=_page_vertical(spec_file_name))
    ref_path, _, fragment = ref_string.partition("#/$defs/")
    fragment = fragment or None
    raw_name = Path(ref_path).name.replace(".json", "")
    is_ucp = "ucp.json" in ref_string

    link_text = _link_text(raw_name, fragment, is_ucp)
    anchor = _link_anchor(raw_name, fragment, is_ucp)

    # For polymorphic types in response mode, keep the base anchor name to
    # match markdown headings like "Line Item", but label it as a response.
    is_plain_name = (
      not fragment
      and "." not in raw_name
      and not raw_name.endswith(("_resp", "_req"))
    )
    if (
      is_plain_name
      and ctx.io_type == "response"
      and _is_polymorphic_type(ref_string, ctx)
      and not link_text.endswith("Response")
    ):
      link_text = f"{link_text} Response"

    target = _resolve(ref_path or "#", ctx)
    page, anchor = _link_destination(
      target, ref_path, fragment, spec_file_name, anchor
    )
    return f"[{link_text}](site:specification/{page}/#{anchor})"

  # --- Table rendering ---
  def _render_table_from_ref(
    properties_ref, required_list, spec_file_name, ctx
  ):
    """Inline the fields of a referenced schema.

    Args:
    ----
      properties_ref: The `$ref` to inline (optionally with `#/$defs/...`).
      required_list: The list of required properties from the parent schema.
      spec_file_name: The page the table is rendered on.
      ctx: RenderContext of the referencing schema.

    Returns:
    -------
      A string containing a Markdown table representing the schema properties,
      or a message indicating why a table could not be rendered.

    """
    ref_path = properties_ref.split("#", 1)[0].removesuffix("/schema")
    target = _resolve(ref_path or "#", ctx)
    ref_schema_data = _load_schema(target, ctx) if target else None

    if not ref_schema_data:
      # If purely external and not found locally.
      if properties_ref.startswith("http"):
        return f"_See [{properties_ref}]({properties_ref})_"
      # ucp-schema failed or schema not found - fail loudly.
      raise RuntimeError(
        f"Failed to resolve properties_ref='{properties_ref}' "
        f"{get_error_context()}. "
        "Ensure ucp-schema is installed: `cargo install ucp-schema`"
      )

    # Handle embedded anchors (e.g. file.json#/$defs/Something).
    if "#" in properties_ref and "$defs" in properties_ref:
      def_name = properties_ref.split("/")[-1]
      ref_schema_data = ref_schema_data.get("$defs", {}).get(def_name)

    if ref_schema_data and not any(
      key in ref_schema_data for key in ("properties", "allOf", "$ref")
    ):
      ref_schema_data = ref_schema_data.get("schema", ref_schema_data)

    return _render_table_from_schema(
      ref_schema_data, spec_file_name, False, required_list, ctx.at(target)
    )

  def _render_embedded_table(
    properties_list, required_list, spec_file_name, ctx
  ):
    """Render the members of an `allOf` as one table.

    Args:
    ----
      properties_list: The `allOf` members.
      required_list: The list of required properties from the parent schema.
      spec_file_name: The page the table is rendered on.
      ctx: RenderContext of the composing schema.

    Returns:
    -------
      A string containing a Markdown table representing the schema properties,
      or a message indicating why a table could not be rendered.

    """
    if not properties_list:
      return "_No content fields defined._"

    # Special handling for capability: [{"$ref": ...}, {"required": [...]}].
    if (
      len(properties_list) == 2
      and len(properties_list[1].keys()) == 1
      and "required" in properties_list[1]
    ):
      capability_required = properties_list[1].get("required", [])
      ref = properties_list[0].get("$ref")
      if ref:
        return _read_schema_from_defs(
          "capability.json" + ref,
          spec_file_name,
          False,
          capability_required,
          ctx,
        )
      # If the ref was already resolved, render the schema directly.
      return _render_table_from_schema(
        properties_list[0], spec_file_name, False, capability_required, ctx
      )

    # Merge required arrays from all allOf siblings so that requirements
    # declared at any level surface correctly.
    merged_required = list(required_list) if required_list else []
    for item in properties_list:
      for req in item.get("required", []):
        if req not in merged_required:
          merged_required.append(req)

    blocks = []
    for properties in properties_list:
      if len(properties) == 1 and "$ref" in properties:
        blocks.append(
          _render_table_from_ref(
            properties["$ref"], merged_required, spec_file_name, ctx
          )
        )
        continue

      # Skip allOf siblings that only carry constraints (required,
      # anyOf with const-only properties) but define no new fields.
      if not (
        properties.get("properties")
        or properties.get("$ref")
        or properties.get("allOf")
      ):
        continue

      blocks.append(
        _render_table_from_schema(
          properties, spec_file_name, False, merged_required, ctx
        )
      )

    return _dedupe_table_rows(blocks)

  def _render_table_from_schema(
    schema_data,
    spec_file_name,
    need_header=True,
    parent_required_list=None,
    ctx=None,
  ):
    """Render a Markdown table from a schema dictionary.

    Schema dictionary must contain 'properties'. 'required' list is optional.

    Args:
    ----
      schema_data: A dictionary representing the JSON schema.
      spec_file_name: The page the table is rendered on.
      need_header: Optional. Whether to render the header row.
      parent_required_list: Optional. The list of required properties from the
        parent schema.
      ctx: Optional RenderContext (operation view and `$ref` base).

    Returns:
    -------
      A string containing a Markdown table representing the schema properties,
      or a message indicating why a table could not be rendered.

    """
    if not schema_data:
      return "_No content fields defined._"

    ctx = (ctx or RenderContext(vertical=_page_vertical(spec_file_name))).at(
      schema_path_from_url(schema_data.get("$id"))
    )

    def link(ref):
      return create_link(ref, spec_file_name, ctx)

    # A bare "#" is a self-root reference naming the schema being rendered.
    # It carries no filename, so create_link derives an empty anchor and emits
    # a broken "<page>/##" link. Recursive refs are irreducible: ucp-schema
    # preserves them even under --bundle, so the docs layer is the only place
    # that can name them. Resolve against this schema's own $id.
    self_id = schema_data.get("$id")
    self_ref_name = self_id.rsplit("/", 1)[-1] if self_id else None

    def _deref_self(ref_value):
      if ref_value == "#" and self_ref_name:
        return self_ref_name
      return ref_value

    # If schema is ONLY a oneOf, render as prose instead of table.
    if (
      "oneOf" in schema_data
      and not schema_data.get("properties")
      and not schema_data.get("allOf")
      and not schema_data.get("$ref")
    ):
      links = []
      for item in schema_data["oneOf"]:
        if "$ref" in item:
          links.append(link(_deref_self(item["$ref"])))
        elif item.get("type"):
          links.append(f"`{item.get('type')}`")
      if links:
        return (
          "\nThis object MUST be one of the following types: "
          + ", ".join(links)
          + ".\n"
        )

    properties = schema_data.get("properties", {})
    required_list = schema_data.get("required", [])

    if parent_required_list:
      # Preserve required fields from both the embedded child schema and the
      # parent wrapper that referenced it.
      required_list = list(required_list)
      for req in parent_required_list:
        if req not in required_list:
          required_list.append(req)

    if (
      not properties
      and "oneOf" not in schema_data
      and "$ref" not in schema_data
      and ("allOf" not in schema_data or schema_data.get("type") == "array")
    ):
      # Fallback for scalar schemas (Enums, Strings with patterns, etc.).
      s_type = schema_data.get("type")
      enum_val = schema_data.get("enum")
      pattern_val = schema_data.get("pattern")

      if s_type or enum_val:
        desc = schema_data.get("description", "")
        if pattern_val:
          desc += f"\n\n**Pattern:** `{pattern_val}`"
        if enum_val:
          formatted = ", ".join([f"`{v}`" for v in enum_val])
          desc += f"\n\n**Enum:** {formatted}"
        return desc

      return "_No properties defined._"

    md = []
    if need_header:
      md = ["| Name | Type | Requirement | Description |"]
      md.append("| :--- | :--- | :--- | :--- |")

    if "allOf" in properties:
      md.append(
        _render_embedded_table(
          properties.get("allOf", []), required_list, spec_file_name, ctx
        )
      )
      return "\n".join(md)

    if "allOf" in schema_data:
      all_of_list = list(schema_data.get("allOf", []))
      if properties:
        all_of_list.append(
          {
            "properties": properties,
            "required": schema_data.get("required", []),
          }
        )
      md.append(
        _render_embedded_table(all_of_list, required_list, spec_file_name, ctx)
      )
      return "\n".join(md)

    if "$ref" in schema_data:
      md.append(
        _render_table_from_ref(
          schema_data.get("$ref"), required_list, spec_file_name, ctx
        )
      )
      return "\n".join(md)

    for field_name, details in properties.items():
      if field_name == "$ref":
        md.append(
          _render_table_from_ref(details, required_list, spec_file_name, ctx)
        )
        continue

      # Capture the request-requirement annotation before `details` may be
      # reassigned during $ref resolution below.
      ucp_annotation = (
        details.get("ucp_request") if isinstance(details, dict) else None
      )

      f_type = details.get("type", "any")
      ref = _deref_self(details.get("$ref"))
      if not ref and details.get("$id") and details.get("$id") != self_id:
        ref = details.get("$id")

      # Resolve UCP $defs references inline so properties render as
      # expanded tables (with anchors) instead of opaque links.
      # e.g., "$ref": "../../ucp.json#/$defs/error" -> inline the allOf
      if ref and "ucp.json#/$defs/" in ref:
        def_name = ref.split("/")[-1]
        ucp_data = _load_json(UCP_SCHEMA_PATH) or {}
        resolved_def = ucp_data.get("$defs", {}).get(def_name)
        if resolved_def:
          # Merge resolved def into details, preserving embedder's
          # description. The resolved def (e.g. allOf with base +
          # status const) replaces the bare $ref.
          embedder_desc = details.get("description")
          details = dict(resolved_def)
          if embedder_desc:
            details["description"] = embedder_desc
          ref = None
          # The resolved def is usually an allOf with no top-level
          # type; name it (and link its reference section) rather
          # than falling back to "any".
          f_type = details.get("type") or _ucp_def_type(def_name)

      # Check for Array specific logic.
      items = details.get("items", {})
      items_ref = _deref_self(items.get("$ref"))
      if not items_ref and items.get("$id") and items.get("$id") != self_id:
        items_ref = items.get("$id")

      # Special handling for UCP version.
      version_data = None
      if ref and ref.endswith("#/$defs/version"):
        version_data = (
          (_load_json(UCP_SCHEMA_PATH) or {})
          .get("$defs", {})
          .get("version", {})
        )

      # --- Logic to determine Display Type ---
      if "oneOf" in details:
        # Render each branch: a $ref becomes a type link, an inline
        # branch shows its JSON type (matching the prose oneOf renderer
        # above). Without the inline case, a oneOf of scalars such as
        # capability `extends` (string | array) rendered as "OneOf[]".
        parts = []
        for one_of_type in details.get("oneOf", []):
          if "$ref" in one_of_type:
            parts.append(link(_deref_self(one_of_type["$ref"])))
          elif one_of_type.get("type"):
            parts.append(f"`{one_of_type['type']}`")
        f_type = f"OneOf[{', '.join(parts)}]"
      elif ref and version_data:
        f_type = version_data.get("type", "any")
      elif ref:
        # Direct Reference.
        f_type = link(ref)
      elif f_type == "array" and items_ref:
        # Array of References.
        f_type = f"Array[{link(items_ref)}]"
      elif f_type == "array":
        # Array of primitives, or of a composed/bundled item whose type
        # is not stated inline (e.g. items defined via allOf, where a
        # $ref to the item type was inlined during resolution). Recover a
        # label from the item type, a $ref link, or a title so the cell
        # does not fall back to the uninformative "any".
        inner_type = items.get("type")
        if not inner_type:
          branches = (
            items["allOf"] if isinstance(items.get("allOf"), list) else [items]
          )
          for branch in branches:
            if not isinstance(branch, dict):
              continue
            if branch.get("$ref"):
              inner_type = link(_deref_self(branch["$ref"]))
              break
            if branch.get("title"):
              inner_type = branch["title"]
              break
          inner_type = inner_type or "object"
        f_type = f"Array[{inner_type}]"
      elif f_type == "any" and _ucp_def_name_for_title(details.get("title")):
        # A ucp.json $def already inlined by bundled resolution: the $ref
        # is gone, but its title still identifies it.
        f_type = _ucp_def_type(_ucp_def_name_for_title(details["title"]))
      elif f_type == "any" and isinstance(details.get("allOf"), list):
        # Composed type (e.g. a $ref plus extra constraints). Show the
        # referenced type(s) instead of "any".
        links = [
          link(_deref_self(branch["$ref"]))
          for branch in details["allOf"]
          if isinstance(branch, dict) and branch.get("$ref")
        ]
        if len(links) == 1:
          f_type = links[0]
        elif links:
          f_type = f"AllOf[{', '.join(links)}]"
        elif details.get("title"):
          f_type = details["title"]
        else:
          # Bundled resolution inlines the branches; if they agree on a
          # JSON type, that is still more precise than "any".
          branch_types = {
            branch.get("type")
            for branch in details["allOf"]
            if isinstance(branch, dict)
          }
          if len(branch_types) == 1 and None not in branch_types:
            f_type = branch_types.pop()

      # --- Handle Description ---
      desc = ""
      # Handle additional description text for constant.
      if "const" in details:
        desc += f"**Constant = {details.get('const')}**. "
      # Special handling for UCP version.
      elif version_data and ref == "#/$defs/version":
        desc += version_data.get("description", "")

      # Get embedder's description, or inherit from ref'd type if omitted.
      embedder_desc = details.get("description")
      if embedder_desc is not None:
        desc += embedder_desc
      elif ref and not ref.startswith("#"):
        ref_schema = _load_json(_resolve(ref, ctx))
        if ref_schema:
          desc += ref_schema.get("description", "")

      # --- Handle Enum ---
      enum_values = details.get("enum")
      if enum_values and isinstance(enum_values, list):
        # Format values like: `val1`, `val2`.
        formatted_enums = ", ".join([f"`{str(v)}`" for v in enum_values])
        # Add a line break if description exists, then append Enum list.
        if desc:
          desc += "<br>"
        desc += f"**Enum:** {formatted_enums}"

      # --- Handle Requirement (per request op + response) ---
      requirement = _field_requirement(
        field_name, ucp_annotation, required_list
      )

      md.append(f"| {field_name} | {f_type} | {requirement} | {desc} |")

    return "\n".join(md)

  def _read_schema_from_defs(
    entity_name,
    spec_file_name,
    need_header=True,
    parent_required_list=None,
    ctx=None,
  ):
    """Render a table for a `<file>.json#/<pointer>` definition.

    Args:
    ----
      entity_name: e.g. 'discount.json#/$defs/allocation'. The file part is
        resolved relative to `ctx.base`, else by name within the vertical.
      spec_file_name: The page the table is rendered on.
      need_header: Whether to render the header row (and description).
      parent_required_list: Required properties from the parent schema.
      ctx: Optional RenderContext of the caller.

    """
    if ".json#/" not in entity_name:
      raise ValueError(
        f"Invalid entity name format for def: {entity_name}"
        f"{get_error_context()}"
      )
    file_part, pointer = entity_name.split(".json#", 1)
    file_part += ".json"
    pointer = "#" + pointer

    ctx = ctx or RenderContext(vertical=_page_vertical(spec_file_name))
    full_path = _resolve(file_part, ctx)
    if full_path is None:
      raise FileNotFoundError(
        f"Schema file '{file_part}' not found in any schema"
        f" directory{get_error_context()}."
      )

    # Use ucp-schema to resolve the full file with bundling.
    bundled = _resolve_schema(full_path, bundle=True)
    embedded_schema_data = _resolve_json_pointer(pointer, bundled)
    if embedded_schema_data is None:
      raise RuntimeError(
        f"Definition '{pointer}' not found in '{full_path}'"
        f"{get_error_context()}"
      )
    # Resolve internal refs (like #/$defs/base) against the bundled root.
    embedded_schema_data = _resolve_internal_all_of(
      embedded_schema_data, bundled
    )

    table = _render_table_from_schema(
      embedded_schema_data,
      spec_file_name,
      need_header,
      parent_required_list,
      RenderContext(base=full_path, vertical=ctx.vertical),
    )
    desc = embedded_schema_data.get("description", "")
    # Scalar schemas (a string/enum with no properties or composition) already
    # embed their description in the rendered fallback table; prepending it
    # here would duplicate it. Only structured schemas — whose table is a
    # property grid that omits the description — need the description
    # prepended.
    is_structured = any(
      key in embedded_schema_data
      for key in ("properties", "allOf", "oneOf", "$ref")
    )
    if desc and need_header and is_structured:
      return f"{desc}\n\n{table}"
    return table

  def _resolves_to_shared_type(ref_path):
    """Return path if ref_path identifies a `common/types/` primitive.

    Scope is intentionally narrow: only schemas under
    `source/schemas/common/types/` have canonical entries eligible for
    link-only rendering on capability pages. Callers render fields inline by
    default and use this lookup only when they explicitly opt out.

    Vertical-namespaced types under `<vertical>/types/` always render inline
    because they have no canonical shared-type entry. Render duplication is
    safe because every table is generated from the same JSON source.

    Cross-references emitted inside any rendered table continue to
    route to `reference.md` via `create_link` (the redirect rule
    introduced in #226 is unchanged), so anchor consistency holds
    end-to-end regardless of which pages render a given type inline.

    This lookup assumes that filenames at `common/` root remain
    disjoint from `common/types/`. If a future schema introduces a
    basename collision, the rule here will need explicit
    disambiguation.
    """
    name = Path(str(ref_path).split("#", 1)[0]).stem
    candidate = COMMON_TYPES_DIR / (name + ".json")
    return candidate if candidate.exists() else None

  def _render_shared_type_link(canonical_name, spec_file_name):
    """Emit a Markdown link to the `reference.md` entry for a shared type.

    Used in place of inline-rendering a `common/types/` table on a
    capability page (#412). `create_link` already routes `common/` schemas
    to `reference.md`, so we reuse it to keep the anchor scheme
    consistent with cross-references emitted from inside other tables.

    `canonical_name` must be the suffix-stripped base name (with or
    without a leading `types/`), never the raw macro argument.
    `reference.md` emits exactly one anchor per schema file -- one
    heading per file, one anchor per heading -- and does not emit
    per-variant anchors. A raw argument still carrying an operation suffix would
    cause `create_link` to bake the variant into the anchor and target
    a heading that does not exist on `reference.md`.
    """
    # Normalize canonical_name into a ref-style path so create_link's
    # anchor logic matches the heading produced by
    # auto_generate_schema_reference on reference.md.
    ref = (
      canonical_name
      if canonical_name.startswith("types/")
      else f"types/{canonical_name}"
    )
    if not ref.endswith(".json"):
      ref = ref + ".json"
    link = create_link(ref, spec_file_name)
    # The trailing reference must use the `site:` absolute scheme
    # (handled by the site-urls plugin), not a relative `reference.md`
    # link. A relative link resolves from the source file's directory,
    # so callers from any subdirectory page would otherwise target a
    # non-existent `<subdir>/reference.md`.
    return (
      f"See {link} in the [Schema Reference](site:specification/reference/) "
      f"for the canonical field definition."
    )

  # --- MACRO 1: For Standalone JSON Schemas ---
  @env.macro
  def schema_fields(entity_name, spec_file_name, render_inline=True):
    """Parse a standalone JSON Schema file and render a table.

    Usage: {{ schema_fields('buyer', 'shopping/checkout') }}

    Suffixes control schema resolution direction:
    - 'cart_resp' -> resolves cart.json as response schema
    - 'cart_create_req' -> resolves cart.json as request schema (op=create)
    - 'buyer' -> resolves buyer.json as response schema (default)

    Bare names resolve within the calling page's vertical (e.g. 'buyer' on a
    food page is food/types/buyer.json); names may also be qualified
    ('food/types/buyer', 'types/context').

    For schemas under `common/types/` (cross-vertical primitives),
    callers from pages other than `reference.md` can selectively receive a
    Markdown link to the canonical entry on `reference.md` or an
    inline table based on the `render_inline` value.

    Args:
    ----
      entity_name: Schema name with optional suffix (e.g., 'cart_resp').
      spec_file_name: Spec page for link generation (e.g., 'shopping/cart').
      render_inline: A boolean that determines whether common types
        should be rendered inline or redirect to reference.md. Has a
        default value of True to always force inline rendering.

    """
    base_name, direction, operation = parse_entity_name(entity_name)

    # By default, `render_inline` is always true to promote better readability,
    # but callers can override it to false to explicitly trigger the redirect
    # rendering for `common/types` schemas. reference.md itself always renders
    # full tables via auto_generate_schema_reference. base_name is passed
    # (suffix stripped) so the link anchor targets the canonical heading.
    if (
      not render_inline
      and spec_file_name != REFERENCE_PAGE
      and _resolves_to_shared_type(base_name) is not None
    ):
      return _render_shared_type_link(base_name, spec_file_name)

    ctx = RenderContext(
      io_type=direction,
      operation_id=operation,
      vertical=_page_vertical(spec_file_name),
    )
    full_path = _resolve(base_name, ctx)
    if full_path is None:
      raise FileNotFoundError(
        f"Schema '{base_name}' not found in any schema directory"
        f"{get_error_context()}."
      )

    # Resolve WITHOUT bundling to preserve $refs for hyperlinks.
    resolved_schema = _resolve_schema(full_path, direction, operation)
    return _render_table_from_schema(
      resolved_schema, spec_file_name, ctx=ctx.at(full_path)
    )

  @env.macro
  def extension_schema_fields(entity_name, spec_file_name, render_inline=True):
    """Render a table for a definition inside a JSON Schema file.

    Usage:
      {{ extension_schema_fields('fulfillment.json#/$defs/fulfillment_option',
                                 'shopping/extensions/fulfillment') }}

    When the embedded schema lives under `common/types/` and `render_inline` is
    False, the macro emits a link to the canonical entry on `reference.md`
    instead of render the table inline. Vertical-namespaced extensions
    always render inline.

    Args:
    ----
      entity_name: The name of the schema entity embedded in the extension
        (e.g., 'fulfillment.json#/$defs/fulfillment_option').
      spec_file_name: The name of the spec file indicating where the dictionary
        should be rendered (e.g., "shopping/checkout").
      render_inline: A boolean that determines whether common types should be
        rendered inline or redirect to reference.md. Has a default value
        of True to always force inline rendering.

    """
    # Redirect to reference.md only when `<file>.json` resolves to a
    # `common/types/` schema and `render_inline` is False; vertical-namespaced
    # extensions keep their inline render so same-page `$defs` anchors
    # continue to resolve.
    if (
      not render_inline
      and spec_file_name != REFERENCE_PAGE
      and ".json#" in entity_name
      and _resolves_to_shared_type(entity_name.split(".json#", 1)[0])
    ):
      return create_link(entity_name, spec_file_name)
    return _read_schema_from_defs(entity_name, spec_file_name)

  def _render_reference_entry(schema_file, schema_data, spec_file_name):
    """Render one auto-generated reference entry (lines), or [] to skip."""
    title = schema_data.get("title", schema_file.stem.replace("_", " ").title())
    ctx = RenderContext(base=schema_file, vertical=vertical_of(schema_file))
    heading = f"### {title}{_reference_anchor_tag(schema_file)}\n"

    defs = schema_data.get("$defs", {})
    is_extension = "Extension" in schema_data.get("title", "")
    if is_extension and defs:
      lines = [heading]
      rel_path = schema_file.relative_to(SCHEMAS_DIR).as_posix()
      for def_name, def_schema in defs.items():
        table = _read_schema_from_defs(
          f"{rel_path}#/$defs/{def_name}", spec_file_name, ctx=ctx
        )
        if table == "_No properties defined._":
          continue
        def_title = def_schema.get("title", def_name.replace("_", " ").title())
        anchor_tag = _reference_anchor_tag(schema_file, def_name)
        lines += [f"#### {def_title}{anchor_tag}\n", table, "\n"]
      return [*lines, "\n---\n"]

    if is_extension and not any(
      schema_data.get(key) for key in ("properties", "allOf", "oneOf", "$ref")
    ):
      return []

    table = _render_table_from_schema(schema_data, spec_file_name, ctx=ctx)
    if table == "_No properties defined._":
      return []
    return [heading, table, "\n---\n"]

  @env.macro
  def auto_generate_schema_reference(
    sub_dir=".",
    spec_file_name=REFERENCE_PAGE,
    include_extensions=True,
    include_capability=True,
    base_dir=None,
  ):
    """Scan a dir for JSON schemas and generate documentation.

    Scan a subdirectory for .json files and generate documentation for each
    schema found. Headings of vertical schemas also carry a path-qualified
    anchor (e.g. `#food-types-fulfillment`) used by cross-reference links,
    since titles may collide across and within verticals.

    Args:
    ----
      sub_dir: The subdirectory to scan, relative to base_dir.
      spec_file_name: The name of the spec file for link generation.
      include_extensions: If true, includes schemas with 'Extension' in title.
      include_capability: If true, includes schemas without 'Extension' in
        title.
      base_dir: The namespace directory to scan, e.g. 'source/schemas/common'
        or 'source/schemas/food'. Required.

    """
    if not base_dir:
      raise ValueError(
        "auto_generate_schema_reference requires base_dir (e.g. "
        f"'source/schemas/common'){get_error_context()}."
      )
    scan_path = _normalize(Path(base_dir) / sub_dir)
    if not scan_path.is_dir():
      return f"<p><em>Schema directory not found: {scan_path}</em></p>"

    schema_files = sorted(f for f in scan_path.iterdir() if f.suffix == ".json")
    if not schema_files:
      return f"<p><em>No schema files found in {scan_path}</em></p>"

    output = []
    for schema_file in schema_files:
      schema_data = _load_json(schema_file)
      if not schema_data:
        output += [
          f"### {schema_file.stem}\n",
          f"<p><em>Could not load schema for entity: {schema_file}</em></p>",
          "\n---\n",
        ]
        continue
      is_extension = "Extension" in schema_data.get("title", "")
      if (is_extension and not include_extensions) or (
        not is_extension and not include_capability
      ):
        continue
      output += _render_reference_entry(
        schema_file, schema_data, spec_file_name
      )

    return "\n".join(output)

  # --- MACRO 2: For Standalone JSON Extensions ---
  @env.macro
  def extension_fields(entity_name, spec_file_name, target="checkout"):
    """Parse an extension schema file and render a table from its $defs.

    Usage: {{ extension_fields('discount', 'shopping/extensions/discount') }}

    Args:
    ----
      entity_name: The name of the extension schema (e.g., 'discount'),
        resolved within the calling page's vertical.
      spec_file_name: The name of the spec file indicating where the dictionary
        should be rendered (e.g., "shopping/extensions/fulfillment").
      target: Optional. The core schema name that is being extended (e.g.,
        "checkout", "cart"). Defaults to "checkout".

    """
    ctx = RenderContext(vertical=_page_vertical(spec_file_name))
    full_path = _resolve(entity_name, ctx)
    data = _load_json(full_path)
    if data is None:
      raise RuntimeError(
        f"Error loading extension '{entity_name}'{get_error_context()}"
      )
    ctx = ctx.at(full_path)

    # Extension schemas have their composed type in $defs, keyed by the
    # extended schema (e.g. `checkout` or `dev.ucp.shopping.checkout`).
    composed = [
      (key, schema_def)
      for key, schema_def in data.get("$defs", {}).items()
      if isinstance(schema_def, dict) and "allOf" in schema_def
    ]
    # Prefer the requested target, then fall back to any composed type.
    preferred = [
      schema_def
      for key, schema_def in composed
      if key == target or key.endswith("." + target)
    ]
    for schema_def in preferred[:1] + [d for _, d in composed]:
      for item in schema_def["allOf"]:
        if "properties" in item:
          return _render_table_from_schema(item, spec_file_name, ctx=ctx)

    raise RuntimeError(
      f"Could not find extension properties for target '{target}' "
      f"in '{entity_name}'{get_error_context()}"
    )

  # --- MACRO 3: For Transport Operations ---
  @env.macro
  def method_fields(operation_id, file_name, spec_file_name, io_type=None):
    """Extract Request/Response schemas for a specific OpenAPI operationId.

    Args:
    ----
      operation_id: The `operationId` of the OpenAPI operation to document.
      file_name: The name of the OpenAPI file to read.
      spec_file_name: The name of the spec file indicating where the dictionary
        should be rendered (e.g., "shopping/checkout").
      io_type: Optional. Specifies whether to render 'request', 'response', or
        both (if None).

    """
    try:
      data = _load_openapi(file_name)
    except (FileNotFoundError, json.JSONDecodeError) as e:
      raise RuntimeError(
        f"Error processing OpenAPI: {e}{get_error_context()}"
      ) from e

    # 1. Find the Operation Object by ID (search paths first, then webhooks).
    operation, path_parameters = _find_operation(
      data, operation_id, include_webhooks=True
    )
    if not operation:
      raise ValueError(
        f"Operation ID `{operation_id}` not found{get_error_context()}."
      )

    # 2. Extract Request Schema.
    req_content = operation.get("requestBody", {}).get("content", {})
    req_schema = req_content.get("application/json", {}).get("schema", {})

    # 3. Extract Parameters (Path + Operation).
    all_parameters = path_parameters + operation.get("parameters", [])

    # 4. Extract Response Schema.
    res_schema = {}
    responses = operation.get("responses", {})
    for code in ("200", "201"):
      if code in responses:
        res_content = responses[code].get("content", {})
        res_schema = res_content.get("application/json", {}).get("schema", {})
        break

    # Targeted reference resolution: only resolve the top-level ref and
    # 'allOf' children (e.g. "complete_checkout") without expanding every
    # property.
    def resolve_structure(schema):
      if not schema:
        return schema
      if "$ref" in schema and schema["$ref"].startswith("#/"):
        schema = _resolve_json_pointer(schema["$ref"], data) or schema
      return _resolve_internal_all_of(schema, data)

    req_schema = resolve_structure(req_schema)
    res_schema = resolve_structure(res_schema)

    # Refs inside the OpenAPI document are relative to the OpenAPI file.
    base_ctx = RenderContext(
      operation_id=operation_id,
      base=_normalize(OPENAPI_DIR / file_name),
      vertical=_page_vertical(spec_file_name),
    )
    output = ""

    # -- Render Request --
    if io_type is None or io_type == "request":
      param_props = {}
      param_required_fields = []
      for param in all_parameters:
        # Resolve param refs explicitly if needed.
        if "$ref" in param and param["$ref"].startswith("#/"):
          param = _resolve_json_pointer(param["$ref"], data) or param

        # Filter out headers (transport-specific).
        if param.get("in") == "header":
          continue
        name = param.get("name", "")
        if not name:
          continue

        # Convert to schema property format.
        prop_schema = param.get("schema", {}).copy()
        if "description" in param:
          prop_schema["description"] = param["description"]

        # Add additional annotation for path parameters.
        if param.get("in", "") == "path":
          prop_schema["description"] = (
            prop_schema.get("description", "") + "Defined in path."
          )
        param_props[name] = prop_schema
        if param.get("required"):
          param_required_fields.append(name)

      param_schema = None
      if param_props:
        param_schema = {
          "properties": param_props,
          "required": param_required_fields,
        }

      # 5. Combine Parameters and Request Body into a single "Inputs" schema.
      if param_schema and req_schema:
        combined_schema = {"properties": {"allOf": [param_schema, req_schema]}}
      else:
        combined_schema = param_schema or req_schema

      if combined_schema:
        req_ctx = dataclasses.replace(base_ctx, io_type="request")
        output += "**Inputs**\n\n"
        output += (
          _render_table_from_schema(
            combined_schema, spec_file_name, ctx=req_ctx
          )
          + "\n\n"
        )
      else:
        output += "_No inputs defined._\n\n"

    # -- Render Output --
    if io_type is None or io_type == "response":
      if res_schema:
        if io_type is None:
          output += "**Output**\n\n"
        res_ctx = dataclasses.replace(base_ctx, io_type="response")
        output += (
          _render_table_from_schema(res_schema, spec_file_name, ctx=res_ctx)
          + "\n\n"
        )
      else:
        output += "_No output defined._\n\n"

    return output

  # --- Shared "Specific Header Requirements" prose ---
  header_requirements_map = {
    "ucp_agent": (
      "* **UCP-Agent**: All requests **MUST** include the `UCP-Agent` header\n"
      "    containing the platform profile URI using Dictionary Structured\n"
      "    Field syntax ([RFC 8941]"
      '(https://datatracker.ietf.org/doc/html/rfc8941){target="_blank"}).\n'
      '    Format: `profile="https://platform.example/profile"`.'
    ),
    "idempotency_key": (
      "* **Idempotency-Key**: Operations that modify state **SHOULD** support\n"
      "    idempotency. When provided, the server **MUST**:\n"
      "    1. Store the key with the operation result for at least 24 hours.\n"
      "    2. Return the cached result for duplicate keys whose request body"
      " matches the original.\n"
      "    3. Return `409 Conflict` if the key is reused with a mismatched"
      " body.\n"
      "    See [Message Signatures — Idempotency Key Requirements]"
      "(../../signatures.md#replay-protection)\n"
      "    for the full payload-matching contract."
    ),
  }

  @env.macro
  def header_requirements(*keys):
    """Render shared 'Specific Header Requirements' bullets by key."""
    try:
      return "\n".join(header_requirements_map[k] for k in keys)
    except KeyError as exc:
      raise ValueError(
        f"Unknown header requirement {exc}{get_error_context()}."
      ) from exc

  # --- MACRO 4: For HTTP Headers ---
  @env.macro
  def header_fields(operation_id, file_name):
    """Extract HTTP headers for a specific OpenAPI operationId.

    Args:
    ----
      operation_id: The `operationId` of the OpenAPI operation.
      file_name: The name of the OpenAPI file to read.

    """
    try:
      data = _load_openapi(file_name)
    except (FileNotFoundError, json.JSONDecodeError) as e:
      raise RuntimeError(
        f"Error processing OpenAPI: {e}{get_error_context()}"
      ) from e

    # 1. Find the Operation Object by ID.
    operation, path_parameters = _find_operation(
      data, operation_id, include_webhooks=False
    )
    if not operation:
      raise ValueError(
        f"Operation ID `{operation_id}` not found{get_error_context()}."
      )

    # 2. Extract Request Headers (Path + Operation parameters).
    req_headers = []
    for param in path_parameters + operation.get("parameters", []):
      if "$ref" in param:
        param = _resolve_json_pointer(param["$ref"], data)
        if not param:
          continue
      if param.get("in") == "header":
        req_headers.append(param)

    # 3. Extract Response Headers (Assumes 200 OK).
    res_headers_defs = (
      operation.get("responses", {}).get("200", {}).get("headers", {})
    )
    res_headers = []
    for name, header in res_headers_defs.items():
      if "$ref" in header:
        resolved = _resolve_json_pointer(header["$ref"], data)
        # If ref not resolved, just use name.
        header = resolved or {"description": "Ref not resolved"}
      res_headers.append({**header, "name": name})

    if not req_headers and not res_headers:
      return "_No headers defined._"

    def render_headers_table(headers_list):
      """Render a list of headers into a Markdown table."""
      md_table = ["| Header | Required | Description |"]
      md_table.append("| :--- | :--- | :--- |")
      for h in headers_list:
        name = f"`{h.get('name')}`"
        required = "**Yes**" if h.get("required") else "No"
        # Handle line breaks in description.
        desc = h.get("description", "").replace("\n", "<br>")
        md_table.append(f"| {name} | {required} | {desc} |")
      return "\n".join(md_table)

    output_parts = []
    if req_headers:
      output_parts.append(
        "**Request Headers**\n\n" + render_headers_table(req_headers)
      )
    if res_headers:
      output_parts.append(
        "**Response Headers**\n\n" + render_headers_table(res_headers)
      )
    return "\n\n".join(output_parts)
